version: "3"

services:
  db:
    image: postgres:11.4-alpine
    container_name: django-db
    env_file: .env
  web:
    build: .
    container_name: django-web
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      # 1ならデバックモード
      - DEBUG=1
      - SECRET_KEY=hoge
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_DB=django_db
      - DATABASE_USER=django_db_user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
